### ISSUE TITLE
Nimble install error (Windows)

### ISSUE THREAD

**Issue by eugenesvk** [PMunch/nimcr#11]
There is an error when installing nimcr with `nimble install nimcr1`:
```
`...Temp\nimble_10464\githubcom_PMunchnimcr\nimcr.nim(55, 17) Error: expression 'execShellCmd("attrib +H " & exeName)' is of type 'int' and has to be discarded;`
```
appending `discard` to https://github.com/PMunch/nimcr/blob/master/nimcr.nim#L55 seems to work
(by the way, the command did indeed add a hidden attribute to the file in my test a single script :) )

**Comment by PMunch** [comment]
Congratulations, you appear to be the first person to run this on Windows (or at least the first in a while). Glad you found this bug, and thanks to @0xACE for fixing it!
