### ISSUE TITLE
spaces cause incorrect argument passing

### ISSUE THREAD

**Issue by AvdN** [PMunch/nimcr#3]
If you call `examples/testfile.nim klm "abc def"` from the shell, the output will be 
```
Hello World!
@["klm", "abc", "def"]
```
which is incorrect as `"abc def"` is not passed as a single argument to `examples/.testfile`.

**Comment by PMunch** [comment]
This is a work-around for limitations with shebangs IIRC, and the system is outlined here: https://github.com/PMunch/nimcr#passing-options

**Comment by AvdN** [comment]
@PMunch  This could also be solved while invoking a shell, by checking each element of args and adding quotes around those that need quoting to survive the shell splitting the arguments again (before calling the executable). So I don't really see the relation.

**Comment by PMunch** [comment]
Oh wait, my bad. I was mixing this with another issue. Yeah that's not supposed to happen.
